# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c66dfc07a897528c58a0fbb655fd4c95c7bc1cee9da316b04eaa64f0eead4f92e3767a7d80e6526a72cfb567bfa90671600bc2c148f106dec0ed2c20eb0a0145

test:
  secret_key_base: bffd30e238f9e8de3900fd89825c9622097ca4211e795d305b30c5b1f5ac6fcc8ee1ba75bc7d9e2dfc1d1322cf1b28adffc0c6bbeaca66f91659a76213ebad97

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
